### ISSUE TITLE
Use nunique

### ISSUE THREAD

**Issue by sen1** [sking963/codecademy_bio#1]
https://github.com/sking963/codecademy_bio/blob/96f51da5917bf175cc5b69332a250ff8af173d33/biodiversity.py#L69-L82

You had it. On top, you used `nunique()` to get the number of species which is the correct answer. Below is nothing but adding a sorting method. `count()` is a wrong answer to count species. Not sure why you changed it. If you have `['cow','cow','dog']` then `count()` will give you 3 but `nunique()` will give you 2, which is the correct answer.

**Comment by sking963** [comment]
Fixed with commit dd9a540c06d6e051a65ac310f7e3b1744e031da5
