### ISSUE TITLE
Alternate way

### ISSUE THREAD

**Issue by sen1** [sking963/codecademy_bio#3]
https://github.com/sking963/codecademy_bio/blob/96f51da5917bf175cc5b69332a250ff8af173d33/biodiversity.py#L112-L114

The first set of parenthesis is redundant. Here is an alternate easy way:
```
species['is_protected'] = species.conservation_status != 'No Intervention'
```

**Comment by sking963** [comment]
I'm using parenthesis instead of a line continuation, so I don't think they are 100% redundant but point taken.
