### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by sen1** [sking963/codecademy_bio#6]
Overall, this was a beautifully done project; great job!

Your python code was readable. I pointed out few minor issues which will make your code more efficient. 

The Matplotlib visualizations were gorgeous. You went above-and-beyond by learning about style sheets and adding labels to your bar charts. Each visualization communicated your points very well.

Presentation: Nice color theme. Liked the pictures of the deer and the waterfall. Your analysis results were nicely presented. A conclusion/summary slide is missing. Always add that for readers who just want the summary of your findings without going through the whole presentation.

Overall pretty nicely done project. I hope that you get a chance to play around with this dataset (or another) and do more research.

**Comment by sking963** [comment]
Thanks!
